# Generated by Django 4.2.2 on 2023-07-04 13:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copies', '0001_initial'),
        ('lendings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lending',
            name='copy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leadings', to='copies.copy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lending',
            name='expire_date',
            field=models.DateField(default=datetime.date(2023, 7, 11)),
        ),
    ]
