# Generated by Django 4.2.2 on 2023-07-06 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendings', '0002_lending_copy_alter_lending_expire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lending',
            name='is_avaliable',
        ),
        migrations.AddField(
            model_name='lending',
            name='is_close',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lending',
            name='expire_date',
            field=models.DateField(default=datetime.date(2023, 7, 13)),
        ),
    ]
