# Generated by Django 4.2.2 on 2023-07-09 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendings', '0003_remove_lending_is_avaliable_lending_is_close_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending',
            name='expire_date',
            field=models.DateField(default=datetime.date(2023, 7, 16)),
        ),
    ]
